#!/usr/bin/expect -f

set timeout 30
set host "shell.r6.websupport.sk"
set port "28156"
set user "uid6030767"
set pass "d30440856e"

spawn ssh -o StrictHostKeyChecking=no $user@$host -p $port

expect {
    "*password:*" {
        send "$pass\r"
    }
}

expect {
    "*$*" {
        send "php -r 'mysqli_report(MYSQLI_REPORT_OFF); \$hosts = array(\"127.0.0.1\", \"localhost\", \"mariadb105.websupport.sk\", \"mariadb108.websupport.sk\", \"mariadb106.websupport.sk\", \"mariadb104.websupport.sk\", \"mariadb103.websupport.sk\", \"mariadb102.websupport.sk\", \"mariadb101.websupport.sk\", \"mariadb109.websupport.sk\", \"mariadb110.websupport.sk\", \"mariadb111.websupport.sk\", \"mariadb112.websupport.sk\", \"mariadb113.websupport.sk\"); foreach (\$hosts as \$h) { \$link = @mysqli_connect(\$h, \"WAOnBTy9\", \"/A=9*BQTD]rVbUZ|?=L)\", \"VR4rJ0oH\"); if (\$link) { echo \"SUCCESS: \$h\\n\"; mysqli_close(\$link); } else { echo \"FAIL \$h\\n\"; } }'\r"
    }
}

expect {
    "*$*" {
        send "exit\r"
    }
}
expect eof
