name: Deploy to Firebase Hosting on Merge

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: any
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Create Dummy Env File
        run: touch .env

      - name: Build Web
        run: |
          flutter build web --release --no-tree-shake-icons \
            --dart-define=BACKEND_MODE=supabase \
            --dart-define=SUPABASE_URL=${{ secrets.SUPABASE_URL }} \
            --dart-define=SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }} \
            --dart-define=GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }}

      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/1007297424308/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'
          service_account: 'github-action-1265342369@goldtaxi-202ff.iam.gserviceaccount.com'

      - name: Deploy to Firebase Hosting
        run: npx -y firebase-tools@latest deploy --only hosting:goldtaxi-202ff --project goldtaxi-202ff
